// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCihK4hbNaxZUp2FJyrbZ_P0smvMrSgmKQ',
    appId: '1:72959749880:web:b3aa02a4c4a131eea1d50d',
    messagingSenderId: '72959749880',
    projectId: 'monolearn-241ca',
    authDomain: 'monolearn-241ca.firebaseapp.com',
    databaseURL: 'https://monolearn-241ca-default-rtdb.firebaseio.com',
    storageBucket: 'monolearn-241ca.appspot.com',
    measurementId: 'G-179QJ1LWBS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDUgPsBvdfstxflx-r2XPhuT5twIsBD8UE',
    appId: '1:72959749880:android:66f04a87de36af0ea1d50d',
    messagingSenderId: '72959749880',
    projectId: 'monolearn-241ca',
    databaseURL: 'https://monolearn-241ca-default-rtdb.firebaseio.com',
    storageBucket: 'monolearn-241ca.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB8kLMybsW9xHtYUFbAOOYwsn2gPp20qSs',
    appId: '1:72959749880:ios:0504d0b84abf8836a1d50d',
    messagingSenderId: '72959749880',
    projectId: 'monolearn-241ca',
    databaseURL: 'https://monolearn-241ca-default-rtdb.firebaseio.com',
    storageBucket: 'monolearn-241ca.appspot.com',
    androidClientId: '72959749880-m7g4u62kt3ncvqo16rd00l4glg1s4pud.apps.googleusercontent.com',
    iosClientId: '72959749880-8b2dbbe434jt77aa508tbvt6agoap4a3.apps.googleusercontent.com',
    iosBundleId: 'com.codewithmaro.wordie',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB8kLMybsW9xHtYUFbAOOYwsn2gPp20qSs',
    appId: '1:72959749880:ios:79fa6f339eb36ec6a1d50d',
    messagingSenderId: '72959749880',
    projectId: 'monolearn-241ca',
    databaseURL: 'https://monolearn-241ca-default-rtdb.firebaseio.com',
    storageBucket: 'monolearn-241ca.appspot.com',
    androidClientId: '72959749880-m7g4u62kt3ncvqo16rd00l4glg1s4pud.apps.googleusercontent.com',
    iosClientId: '72959749880-t5frtfpkeoiekehb8fn1k3v2cb7ge8c4.apps.googleusercontent.com',
    iosBundleId: 'com.codewithmaro.wordie.RunnerTests',
  );
}
